name: Client CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'client-mobile/**'
      - '.github/workflows/client-tests.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'client-mobile/**'
      - '.github/workflows/client-tests.yml'

jobs:
  build:
    runs-on: ubuntu-latest 

    defaults:
      run:
        working-directory: client-mobile

    strategy:
      matrix:
        node-version: [18.x, 20.x] 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'client-mobile/package-lock.json'

    - name: Install dependencies
      run: npm ci 

    - name: Run test suite
      run: npm test
